# Conservative Optimized ExecutorCore Configuration
# Generated by conservative parameter tuning on 2025-07-31 17:38:49

from flujo.application.core.ultra_executor import OptimizationConfig

def get_conservative_optimized_config() -> OptimizationConfig:
    """Get conservative optimized configuration that minimizes overhead."""
    return OptimizationConfig(
        # Memory optimizations - DISABLED (causing overhead)
        enable_object_pool=False,
        enable_context_optimization=False,
        enable_memory_optimization=False,
        object_pool_max_size=100,  # Minimal if enabled
        object_pool_cleanup_threshold=0.9,  # Less aggressive cleanup
        
        # Execution optimizations - SELECTIVE
        enable_step_optimization=False,  # Disable if causing overhead
        enable_algorithm_optimization=False,  # Disable if causing overhead
        enable_concurrency_optimization=False,  # Disable if causing overhead
        max_concurrent_executions=8,  # Conservative concurrency
        
        # Telemetry optimizations - MINIMAL
        enable_optimized_telemetry=False,  # Disable to reduce overhead
        enable_performance_monitoring=False,  # Disable to reduce overhead
        telemetry_batch_size=50,  # Smaller batches
        telemetry_flush_interval_seconds=10.0,  # Less frequent flushing
        
        # Error handling optimizations - MINIMAL
        enable_optimized_error_handling=False,  # Disable if causing overhead
        enable_circuit_breaker=False,  # Disable if causing overhead
        error_cache_size=50,  # Minimal cache
        circuit_breaker_failure_threshold=10,  # Less sensitive
        circuit_breaker_recovery_timeout_seconds=60,  # Longer recovery
        
        # Cache optimizations - MINIMAL
        enable_cache_optimization=False,  # Disable if causing overhead
        cache_compression=False,
        cache_ttl_seconds=7200,  # Longer TTL
        cache_max_size=500,  # Smaller cache
        
        # Performance thresholds - RELAXED
        slow_execution_threshold_ms=2000.0,  # Less sensitive
        memory_pressure_threshold_mb=1000.0,  # Higher threshold
        cpu_usage_threshold_percent=90.0,  # Less aggressive
        
        # Automatic optimization - DISABLED
        enable_automatic_optimization=False,  # Disable to prevent overhead
        optimization_analysis_interval_seconds=300.0,  # Less frequent
        performance_degradation_threshold=0.5,  # Less sensitive
        
        # Backward compatibility
        maintain_backward_compatibility=True,
        allow_runtime_changes=False,  # Disable runtime changes
        config_validation_enabled=False  # Disable validation overhead
    )

# Component-specific conservative parameters
CONSERVATIVE_OBJECT_POOL_CONFIG = {
    "max_pool_size": 50,  # Very small pools
    "max_pools": 10,  # Few pools
    "cleanup_threshold": 0.9,  # Less aggressive cleanup
    "stats_enabled": False  # Disable stats overhead
}

CONSERVATIVE_CONTEXT_MANAGER_CONFIG = {
    "cache_size": 64,  # Very small cache
    "merge_cache_size": 32,  # Very small merge cache
    "ttl_seconds": 7200,  # Longer TTL
    "enable_cow": False,  # Disable COW optimization
    "enable_stats": False  # Disable stats overhead
}

CONSERVATIVE_TELEMETRY_CONFIG = {
    "enable_tracing": False,  # Disable tracing
    "enable_metrics": False,  # Disable metrics
    "enable_sampling": True,
    "sampling_rate": 0.01,  # Very low sampling (1%)
    "batch_size": 10,  # Very small batches
    "flush_interval": 30.0,  # Infrequent flushing
    "enable_stats": False  # Disable stats overhead
}

CONSERVATIVE_RESOURCE_MANAGER_CONFIG = {
    "monitoring_interval": 5.0,  # Less frequent monitoring
    "adaptation_interval": 30.0,  # Less frequent adaptation
    "enable_telemetry": False  # Disable telemetry overhead
}
