# Optimized ExecutorCore Configuration
# Generated by parameter tuning on 2025-07-31 17:37:31

from flujo.application.core.ultra_executor import OptimizationConfig

def get_optimized_config() -> OptimizationConfig:
    """Get optimized configuration based on system characteristics and performance tuning."""
    return OptimizationConfig(
        # Memory optimizations
        enable_object_pool=True,
        enable_context_optimization=True,
        enable_memory_optimization=True,
        object_pool_max_size=500,
        object_pool_cleanup_threshold=0.75,
        
        # Execution optimizations
        enable_step_optimization=True,
        enable_algorithm_optimization=True,
        enable_concurrency_optimization=True,
        max_concurrent_executions=24,
        
        # Telemetry optimizations
        enable_optimized_telemetry=True,
        enable_performance_monitoring=True,
        telemetry_batch_size=400,
        telemetry_flush_interval_seconds=2.0,
        
        # Cache optimizations
        enable_cache_optimization=True,
        cache_ttl_seconds=1800,
        cache_max_size=1000,
        
        # Performance thresholds (optimized)
        slow_execution_threshold_ms=500.0,
        memory_pressure_threshold_mb=250.0,
        cpu_usage_threshold_percent=70.0,
        
        # Automatic optimization
        enable_automatic_optimization=True,
        optimization_analysis_interval_seconds=30.0,
        performance_degradation_threshold=0.15,
        
        # Backward compatibility
        maintain_backward_compatibility=True,
        allow_runtime_changes=True,
        config_validation_enabled=True
    )

# Component-specific optimized parameters
OPTIMIZED_OBJECT_POOL_CONFIG = {
    "max_pool_size": 500,
    "max_pools": 200,
    "cleanup_threshold": 0.75,
    "stats_enabled": True
}

OPTIMIZED_CONTEXT_MANAGER_CONFIG = {
    "cache_size": 1024,
    "merge_cache_size": 512,
    "ttl_seconds": 1800,
    "enable_cow": True,
    "enable_stats": True
}

OPTIMIZED_TELEMETRY_CONFIG = {
    "enable_tracing": True,
    "enable_metrics": True,
    "enable_sampling": True,
    "sampling_rate": 0.5,
    "batch_size": 400,
    "flush_interval": 2.0,
    "enable_stats": True
}

OPTIMIZED_RESOURCE_MANAGER_CONFIG = {
    "monitoring_interval": 0.5,
    "adaptation_interval": 3.0,
    "enable_telemetry": True
}
