#!/bin/bash
#
# DEMONSTRATES FLUJO NESTED LOOP BUG
# Analyzes the actual failing clarification pipeline run
#

cd "$(dirname "$0")"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        DEMONSTRATING FLUJO NESTED LOOP BUG                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Bug: HITL resume in loops creates NESTED loops instead of"
echo "     continuing the current iteration."
echo ""
echo "Evidence: Your clarification pipeline run (20251004_215628)"
echo ""

# Analyze the actual failing run
DEBUG_FILE="20251004_215628_run.json"

if [ ! -f "$DEBUG_FILE" ]; then
    echo "❌ Debug file not found: $DEBUG_FILE"
    echo ""
    echo "To reproduce:"
    echo "  cd /Users/alvaro1/Documents/Coral/Code/cohortgen/projects/clarification"
    echo "  uv run flujo run --debug pipeline.yaml"
    echo "  # Answer 5-6 questions, let agent finish"
    echo "  # Copy debug file: cp debug/[latest].json bug_demo/"
    echo "  # Then run: cd bug_demo && ./DEMO_BUG.sh"
    exit 1
fi

echo "────────────────────────────────────────────────────────────────"
echo "ANALYZING: $DEBUG_FILE"
echo "────────────────────────────────────────────────────────────────"
echo ""

python3 analyze_nested_loops.py "$DEBUG_FILE"

echo ""
echo "────────────────────────────────────────────────────────────────"
echo "WHAT THIS MEANS:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "✅ Expected (depth 1):"
echo "   clarification_loop → iteration 1"
echo "   clarification_loop → iteration 2"
echo "   clarification_loop → iteration 3"
echo "   ...exit when agent says 'finish'"
echo ""
echo "❌ Actual (depth N):"
echo "   clarification_loop"
echo "     └── clarification_loop (NESTED #1)"
echo "         └── clarification_loop (NESTED #2)"
echo "             └── clarification_loop (NESTED #3)"
echo "                 └── ... (continues until timeout)"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "ROOT CAUSE:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "When HITL step pauses and resumes inside a loop:"
echo "  ❌ Flujo creates a NEW nested loop instance"
echo "  ✅ Should continue the CURRENT loop iteration"
echo ""
echo "Result:"
echo "  - exit_expression evaluated in wrong (nested) context"
echo "  - Loop never exits even when agent outputs 'finish'"
echo "  - Pipeline stuck in infinite nested loops"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "FILES:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "📄 Pipeline:         ../pipeline.yaml (in parent directory)"
echo "📄 Debug trace:      $DEBUG_FILE (in this folder)"
echo "📄 Analysis script:  analyze_nested_loops.py"
echo "📄 Full report:      BUG_CONFIRMED.md"
echo "📄 For Flujo team:   FLUJO_TEAM_URGENT.md"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "HOW TO SHARE WITH FLUJO TEAM:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "1. Share this entire folder: bug_demo/"
echo "2. They can run: cd bug_demo && ./DEMO_BUG.sh"
echo "3. All evidence files are included:"
echo "   - DEMO_BUG.sh (this script)"
echo "   - analyze_nested_loops.py (analysis tool)"
echo "   - 20251004_215628_run.json (debug trace)"
echo "   - FLUJO_TEAM_URGENT.md (detailed report)"
echo "   - BUG_CONFIRMED.md (test results)"
echo "   - NESTED_LOOP_STILL_BROKEN.md (technical analysis)"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  BUG CONFIRMED: Nested loops detected in Flujo 0.4.37          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
