version: '0.1'
name: "ExtractGeneratedYaml"
steps:
- name: fetch_data
  agent:
    id: flujo.builtins.http_get
    params:
      url: http://example.com/data
  kind: step
- name: extract_info
  agent:
    id: flujo.builtins.extract_from_text
    params:
      text: '{{ fetch_data.body }}'
      schema: '{ ''title'': ''string'', ''date'': ''string'' }'
  kind: step
- name: save_to_file
  agent:
    id: flujo.builtins.fs_write_file
    params:
      path: /path/to/output.txt
      content: 'Title: {{ extract_info.title }}, Date: {{ extract_info.date }}'
  kind: step
